### ISSUE TITLE
Is this project active?

### ISSUE THREAD

**Issue by semmons99** [mbj/inflecto#10] opened 2015-02-13 21:11 UTC
Is this project active? Are you looking for a maintainer? We're using inflecto and like to push it to a 1.0.0 release.

**Comment by mbj** [comment] 2015-02-13 21:19
@semmons99 The only thing I'd like to do before releasing `1.0.0` is to get it fully mutation covered via [mutant](https://github.com/mbj/mutant). And maybe incorporate: https://github.com/mbj/inflecto/pull/8

In case you wanna help: You could fix the remaining problems with the PR I cited.

**Comment by mbj** [comment] 2015-02-13 21:21
@semmons99 I'd also be happy you could get the remaining mutations killed to reduce the specification / implementation mismatch that is identifiable via mutation testing.

**Comment by abinoam** [comment] 2017-11-01 16:06
Reference: https://github.com/mbj/inflecto/issues/16#issuecomment-341144100

> Sorry, I've literally no time to maintain this library as I do not use it for any of my clients / projects right now.
> My opensource time is negative for years now. If someone wants to take over feel free to do so
> - @mbj 

Hi @mbj,

Inflecto is a really cool gem, congratulations for maintaining it.
I'm writing some "factory" code for myself as I've had some hard time with FactoryGirl and Fabrication for some edge cases.
So, I'll need this constantize, camelize, etc thing to help me out at this factory code.
I wouldn't like to depend on active_support as it does "more" than I want.
At the same time I wouldn't like to reivent the wheel (and worst, in a non optimized way).
I just would like something more focused as inflecto.
So, if I can get this thing working (without ActiveSupport) I'll probably will depend on Inflecto for some time.

And, yes, **I surely can help in the task of maintaining the gem**. Although I don't think I'm a good fit for being in charge of it, as my **main** real life job doesn't depend on programming. Programming is a side thing in my life, so sometimes I just don't have spare time to spend on it. And... I have a lot of work trying to keep HighLine in shape. (https://github.com/JEG2/highline)

If you want to start a conversation about me helping the project or just temporarily taking over it to fix some issues and releasing a new version, my e-mail is abinoam at gmail.com.

Thanks in advance

**Comment by mbj** [comment] 2017-11-01 16:20
@abinoam I think I'd prefer to hand over the gem instead of overseeing maintenance. Are you willing to do this?

**Comment by mbj** [comment] 2017-11-01 16:23
> And, yes, I surely can help in the task of maintaining the gem. Although I don't think I'm a good fit for being in charge of it, as my main real life job doesn't depend on programming. Programming is a side thing in my life, so sometimes I just don't have spare time to spend on it. And... I have a lot of work trying to keep HighLine in shape. (https://github.com/JEG2/highline)

I missed that part, sorry. 

This is the crux of opensource. Stuff will die. This is one of that projects.

If I have any time for OSS I maintain [mutant](https://github.com/mbj/mutant) a signficantly higher scope project than this one. Hence this project is abandon-ware for me right now. It'll literally *never* bubble up my OSS todo list.

If anyone wants to step up and take it: Feel free to do so. But the problem is: TONS of infrastrucutre code uses inflecto, most notably some widely used cloud API, a faulty release can kill a lot of peoples productive work.

And that productive work is funded by companies that never would sponsor any work here. OSS is fucked. The entire model. At least for small infra libs like this one.

**Comment by mbj** [comment] 2017-11-01 16:27
Thinking about the implications to hand over a gem with millions of downloads to someone I do not know, I think its better to hard fork this gem under a new name.

This way I can safely rest in peace I do not hand over the keys to thousands (?) of production deployments that use this code transitively. Likely a point release falls within most peoples dependency resolvers, that would automatically pick it up with all implications.

**Comment by mbj** [comment] 2017-11-01 16:28
@abinoam Not saying you are not trustworthy (or anyone who asked), its simply too risky. I do only know a handful of people I would hand over the gem name. People I worked with for years.

Seriously OSS need a "garbage disposal" protocol ;)

**Comment by abinoam** [comment] 2017-11-01 16:52
I completely understand you @mbj. You don't need to excuse for that.
I'm having a similar issue with HighLine.

https://rubygems.org/gems/highline/versions/1.7.8 (14.819.532 downloads).
https://rubygems.org/gems/highline/versions/2.0.0.pre.develop.2 (3.253 downloads - with 2 years around)

So, I think nobody is testing the prerelease.
And we have been postponing it.
When we finally release it, a lot of people will get angry!

Decisions we made:
- We'll not maintain 1.7.x anymore
- We'll release 2.0.x and it'll break api
- People have 2 choices, just lock highline version to 1.7.x, or upgrade to 2.0.x

**Comment by Ptico** [comment] 2017-11-01 17:14
I use inflecto very often and have some ideas like module builder and small improvements in existing API. I would be happy to maintain the hardfork if you think that this is ok.

**Comment by abinoam** [comment] 2017-11-01 17:16
@mbj,

What would be the advantage of forking and changing the gem name against just releasing a new major version? Releasing a new major version you're stating clearly that there's some breaking changes at the release. People should be responsible for managing  their dependencies.

I'm thinking about the possibility of forking the gem as you suggested, but I would be more comfortable to just make some pre release versions (like I'm doing it at HighLine). And wait some time to see how people test it before releasing the official major release.

Well, you could hold on the rubygems credentials for you and release as you think appropriate or as we can find someone you can trust to be in charge of this. Meanwhile we could just make a pre-release branch and freeze the 0.0.x one.

**Comment by Ptico** [comment] 2017-11-01 17:22
@abinoam @mbj I also don't see a big issue with major version bump. All popular and well-maintained gems (fog-brightbox is a good example) properly locks their deps

**Comment by abinoam** [comment] 2017-11-01 17:23
@Ptico whatever this thread goes into, if forking or just releasing a major version under @mbj blessing, I would like to help with it.

I think @mbj should stay in charge of the releases and keep the gem name (the guy rocks!).
I think, with me and you (@Ptico) helping out in closing issues, merging PRs, fixing bugs, and adding any necessary feature, will make a lot easier to @mbj to stay in charge of it.
This will give us some time to see how things evolve.

**Comment by mbj** [comment] 2017-11-01 18:29
> What would be the advantage of forking and changing the gem name against just releasing a new major version? Releasing a new major version you're stating clearly that there's some breaking changes at the release. People should be responsible for managing their dependencies.

The problem is that this major gem release will literally never happen. Unless I hand someone the repository / gem who than could do an evil point release.

Hence the only real solution IMO is to hard fork the gem under a new name. Even if the fog people would right now stop to use inflecto there will be literally thousand+ individual deployments still be using the old inflecto, which could be affected by an evil point release.

Everybody has my blessing to do whatever they want with the code in this repo, its not even originally "mine" I just packaged it at the time mutant needed the API and I did not want to pull active support.

But I see no way I could give up the gem name. And everybody here who is interested in a better (breaking) API can easily use such a new gem (name).

**Comment by mbj** [comment] 2017-11-01 18:31
> I think @mbj should stay in charge of the releases and keep the gem name (the guy rocks!).

Thx, but this is literally what I do not want. I do NOT want to be involved at all. I'm behind 100+ of OSS issues/tasks that are to me higher priority than this repo. I do not want to add to this backlog, at all. I want it to disappear.

**Comment by mbj** [comment] 2017-11-01 18:35
Another way of stating it: At the time I packaged this code I was by far not happy with its state, and I only ever release when the code in the repo qualifies to my own standards. Look at the difference between this repository and others.

I cannot stand releasing from this state. Nor I can supervise (or even thinking about doing the work) to rescue it. Nor is it even in my area of interest to do this for an inflection library.

My interest in Ruby is negative, I only do ruby for years now for helping my commercial agenda (clients work in consulting work). Without my clients using mutant I'd have exited ruby altogether already.

I use inflecto very often and have some ideas like module builder and small improvements in existing API. I would be happy to maintain the hardfork if you think that this is ok.

Yes please do. I'll happily put a "kill all code + add a readme pointing to the new repo" commit on top of the current master.

**Comment by Ptico** [comment] 2017-11-01 18:53
Ok, we will let you know about new repo. Anyway, thanks for the project and all our collaboration. It was great!

**Comment by mbj** [comment] 2017-11-01 20:02
> @mbj Ok, we will let you know about new repo. Anyway, thanks for the project and all our collaboration. It was great!

thx, same.

**Comment by abinoam** [comment] 2017-11-02 00:53
Thanks a lot for your work at inflecto @mbj!
Let's see if I and @Ptico could stand up with it for another round more.
Tomorrow I'll try to begin helping @Ptico on this.

**Comment by mbj** [comment] 2017-11-02 10:44
> Let's see if I and @Ptico could stand up with it for another round more.
> Tomorrow I'll try to begin helping @Ptico on this.

big thanks!

**Comment by fuelxc** [comment] 2017-11-02 14:11
After talking with our CTO we (@teamsnap) would like to offer to take over the gem.  We already have several OSS projects and our CTO runs the RubyMoney project.

**Comment by mbj** [comment] 2017-11-02 14:29
@fuelxc Feel free to do what ever you want with the code, but I'll not hand over the gem name to anyone as discussed above.

You'll have to release under a different gem name. But ideally sync up with @Ptico he showed great contribution / maintainership skills. His fork is here: https://github.com/Ptico/inflecto

**Comment by Ptico** [comment] 2017-11-02 14:37
@mbj Here it is: https://github.com/Ptico/flexus

@fuelxc we already have a fork, but your contributions are very welcome!

**Closed** 2017-11-02 14:38 UTC
Labels: question
